### ISSUE TITLE
Issue with v1.01

### ISSUE THREAD

**Issue by sivaelid** [RPiks/pico-WSPR-tx#3]
Hi  Roman 

 Thanks for your email responce. I see that a new version v1.01 was released this also did not compile as there was no content in the pico-hf-oscillator folder . I have got it to work by placing the  the contents from your git site in the folder. Not sure why content is mising. 

Simon G8HAM

**Comment by RPiks** [comment]
Hi Simon,

Thank you for the feedback.

This was an issue of v.1.0 due to lack of `submodule init` statement in ./build.sh script.
The bug is fixed since v.1.0.1.

To check:
git clone https://github.com/RPiks/pico-WSPR-tx.git
cd pico-WSPR-tx
./build.sh

Regards,
Roman
R2BDY
