### ISSUE TITLE
Error in 17 m dial frequency ?

### ISSUE THREAD

**Issue by zanco** [RPiks/pico-WSPR-tx#8]
Hi,
In the "quickstart" at number 7 you mention:

"Initialy the operating HF band is 17 meter (WSPR dial frequency is 18106 kHz)."

I think that should read 18104.6 kHz ?

Ben - PE2BZ

**Comment by RPiks** [comment]
Hi Ben,

Sorry for the belated answer, but I really had the hands full.

The frequency of 18104.6 kHz can be set in wsjt-x or jtdx terminal as `dial frequency`. 
However, please look at the wsjt-x's spectrogram carefully: the range of WSPR emission is 1400...1600 Hz. So, you cannot set the TX frequency of your beacon below 18104600 + 1400 = 18106000 Hz. Therefore, the pure dial frequency of WSPR beacon of 17 meter band is 18106 kHz.

With best regards, Roman
R2BDY

**Comment by zanco** [comment]
Understood Roman, thanks for the answer !
